version: '3'

services:
  dinner-service:
    build: ./Dinners
    volumes:
     - ./Dinners:/usr/src/app
    ports:
     - 5001:80

  website:
    image: php:apache
    volumes:
     - ./suggestion_website:/var/www/html
    ports:
     - 5000:80
    depends_on:
     - dinner-service